version: '3'


networks:
  shared_network:


services:
  magic:
    command: mage start divelog
    container_name: magic
    env_file:
      - env.sample
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
    networks:
      - shared_network